# This is a basic workflow to help you get started with Actions
name: Portfolio
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"
        
      # Install project
      - name: Install project
        run: npm install

      # Build project
      - name: Build project
        run: npm run-script build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
